package test.org.mandarax.compiler.reldef10;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import test.org.mandarax.compiler.*;

/**
 * Class representing the relationship <strong>GrandFather</strong>.
 * Generated by org.mandarax.compiler.impl.DefaultCompiler.
 * @version Nov 19, 2010 11:37:07 AM 
 */
public class GrandFatherRel {

	// fields created for slots 
	public MalePerson grandFather = null; 
	public MalePerson grandChild = null;
	
	// constructors
	public GrandFatherRel () {
		super();
	}
	
	public GrandFatherRel ( MalePerson grandFather , MalePerson grandChild ) {
		super();
		this.grandFather=grandFather; 
		this.grandChild=grandChild; 
		
	}

	// standard methods
	@Override
	public boolean equals(Object obj) {
   		if (obj == null) { return false; }
   		if (obj == this) { return true; }
		if (obj.getClass() != getClass()) {
			return false;
		}
   		GrandFatherRel _tmp = (GrandFatherRel) obj;
   		return new EqualsBuilder()
            .append(grandFather, _tmp.grandFather)
            .append(grandChild, _tmp.grandChild)
            .isEquals();
  	}
  
  	@Override
   	public int hashCode() {
    	return new HashCodeBuilder(17, 37)
        	.append(grandFather)
            .append(grandChild)
            .toHashCode();
   	}
   	@Override
   	public String toString() {
    	return new ToStringBuilder(this)
    		.append("grandFather",grandFather)
    		.append("grandChild",grandChild)
    		.toString();
   }
   

}

